Repository woorepie/woorepie-spring, pull requests merged in 2025-06, with the labels that each got.

#78 [FEAT] 마이페이지 수정 및 estate entity 컬럼 추가
  woorepie/src/main/java/com/piehouse/woorepie/customer/controller/CustomerController.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/dto/request/ModifyPassword.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/dto/request/PlusAccountBalance.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/dto/response/GetCustomerAccountResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/entity/Customer.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/service/CustomerService.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/service/implement/CustomerServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/entity/Estate.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/service/implement/EstateRedisServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/subscription/service/implement/SubscriptionServiceImpl.java
  woorepie/src/main/resources/scripts/save_order.lua
Labels: Feature, fix

#87 [FEAT] 알림 기능 개선 및 청약 알림 연동
  woorepie/src/main/java/com/piehouse/woorepie/global/util/NotificationContentUtils.java
  woorepie/src/main/java/com/piehouse/woorepie/notification/controller/NotificationController.java
  woorepie/src/main/java/com/piehouse/woorepie/notification/dto/response/NotificationResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/notification/entity/Notification.java
  woorepie/src/main/java/com/piehouse/woorepie/notification/repository/NotificationRepository.java
  woorepie/src/main/java/com/piehouse/woorepie/notification/service/NotificationService.java
  woorepie/src/main/java/com/piehouse/woorepie/notification/service/implement/NotificationServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/subscription/service/implement/SubscriptionServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/trade/service/implement/TradeRedisServiceImpl.java
Labels: Feature

#91 [FIX] 알림 신청 금액 및 실패자 환불 처리 로직 수정
  woorepie/src/main/java/com/piehouse/woorepie/global/kafka/dto/SubscriptionAcceptMessage.java
  woorepie/src/main/java/com/piehouse/woorepie/global/kafka/service/KafkaConsumerService.java
  woorepie/src/main/java/com/piehouse/woorepie/global/kafka/service/impliment/KafkaConsumerServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/notification/service/implement/NotificationServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/subscription/service/implement/SubscriptionServiceImpl.java
Labels: bug

#100 [TEST] 청약 서비스 로직 단위 테스트 및 시나리오별 Mock 테스트 추가
  woorepie/src/test/java/com/piehouse/woorepie/subscription/service/implement/SubscriptionServiceImplTest.java
Labels: test

#106 [TEST] Trade 서비스 로직 단위 테스트 및 시나리오별 Mock 테스트 추가
  woorepie/src/test/java/com/piehouse/woorepie/trade/service/implement/TradeRedisServiceImplTest.java
  woorepie/src/test/java/com/piehouse/woorepie/trade/service/implement/TradeServiceImplTest.java
Labels: test

#108 [TEST] Notice 서비스 로직 단위 테스트 및 시나리오별 Mock 테스트 추가
  woorepie/src/main/java/com/piehouse/woorepie/notice/controller/NoticeController.java
  woorepie/src/main/java/com/piehouse/woorepie/notice/service/NoticeService.java
  woorepie/src/main/java/com/piehouse/woorepie/notice/service/implement/NoticeServiceImpl.java
  woorepie/src/test/java/com/piehouse/woorepie/notice/service/implement/NoticeServiceImplTest.java
Labels: test

#102 [TEST] customer 서비스 로직 단위 테스트 및 시나리오별 Mock 테스트 추가
  woorepie/src/main/java/com/piehouse/woorepie/agent/repository/AgentRepository.java
  woorepie/src/main/java/com/piehouse/woorepie/agent/service/implement/AgentServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/controller/CustomerController.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/repository/CustomerRepository.java
  woorepie/src/test/java/com/piehouse/woorepie/customer/service/implement/CustomerServiceImplTest.java
Labels: test

#115 [FEAT] Notice API 비로그인 접근 허용
  woorepie/src/main/java/com/piehouse/woorepie/global/config/SecurityConfig.java
  woorepie/src/test/java/com/piehouse/woorepie/estate/service/implement/EstateRedisServiceImplTest.java
Labels: Feature

#116 [FIX] Entity type 변경
  woorepie/src/main/java/com/piehouse/woorepie/agent/dto/response/AgentEstateListResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/agent/service/implement/AgentServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/dto/request/PlusAccountBalance.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/dto/response/GetCustomerAccountResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/dto/response/GetCustomerResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/dto/response/GetCustomerSubscriptionResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/dto/response/GetCustomerTradeResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/entity/Account.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/entity/Customer.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/repository/CustomerRepository.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/service/CustomerService.java
  woorepie/src/main/java/com/piehouse/woorepie/customer/service/implement/CustomerServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/controller/EstateController.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/dto/RedisEstatePrice.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/dto/response/GetEstateDetailsResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/dto/response/GetEstatePriceResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/dto/response/GetEstateSimpleResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/entity/Estate.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/entity/EstatePrice.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/repository/EstateRepository.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/service/EstateRedisService.java
  woorepie/src/main/java/com/piehouse/woorepie/estate/service/implement/EstateRedisServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/global/kafka/dto/OrderCreatedEvent.java
  woorepie/src/main/java/com/piehouse/woorepie/global/kafka/dto/SubscriptionAcceptEvent.java
  woorepie/src/main/java/com/piehouse/woorepie/global/kafka/dto/SubscriptionRequestEvent.java
  woorepie/src/main/java/com/piehouse/woorepie/global/kafka/dto/TransactionCreatedEvent.java
  woorepie/src/main/java/com/piehouse/woorepie/global/kafka/service/impliment/KafkaConsumerServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/global/util/NotificationContentUtils.java
  woorepie/src/main/java/com/piehouse/woorepie/notification/service/NotificationService.java
  woorepie/src/main/java/com/piehouse/woorepie/notification/service/implement/NotificationServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/subscription/dto/request/RegisterEstateRequest.java
  woorepie/src/main/java/com/piehouse/woorepie/subscription/dto/response/GetSubscriptionDetailsResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/subscription/dto/response/GetSubscriptionSimpleResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/subscription/entity/Subscription.java
  woorepie/src/main/java/com/piehouse/woorepie/subscription/scheduler/SubscriptionSyncScheduler.java
  woorepie/src/main/java/com/piehouse/woorepie/subscription/service/implement/SubscriptionServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/trade/dto/request/BuyEstateRequest.java
  woorepie/src/main/java/com/piehouse/woorepie/trade/dto/request/CreateSubscriptionTradeRequest.java
  woorepie/src/main/java/com/piehouse/woorepie/trade/dto/request/RedisCustomerTradeValue.java
  woorepie/src/main/java/com/piehouse/woorepie/trade/dto/request/RedisEstateTradeValue.java
  woorepie/src/main/java/com/piehouse/woorepie/trade/dto/request/SellEstateRequest.java
  woorepie/src/main/java/com/piehouse/woorepie/trade/entity/Trade.java
  woorepie/src/main/java/com/piehouse/woorepie/trade/service/TradeRedisService.java
  woorepie/src/main/java/com/piehouse/woorepie/trade/service/TradeService.java
  woorepie/src/main/java/com/piehouse/woorepie/trade/service/implement/TradeRedisServiceImpl.java
  woorepie/src/main/java/com/piehouse/woorepie/trade/service/implement/TradeServiceImpl.java
  woorepie/src/test/java/com/piehouse/woorepie/customer/service/implement/CustomerServiceImplTest.java
  woorepie/src/test/java/com/piehouse/woorepie/estate/service/implement/EstateRedisServiceImplTest.java
Labels: fix

#121 [FIX] 청약 매물 리스트 조회 필터 수정
  woorepie/src/main/java/com/piehouse/woorepie/estate/entity/EstateStatus.java
  woorepie/src/main/java/com/piehouse/woorepie/subscription/dto/response/GetSubscriptionSimpleResponse.java
  woorepie/src/main/java/com/piehouse/woorepie/subscription/service/implement/SubscriptionServiceImpl.java
Labels: fix
